version: '3.8'
services:
  api:
    build:
      context: .
    volumes:
      - ./:/app/
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    entrypoint: dotnet run