FROM mcr.microsoft.com/dotnet/sdk:5.0
WORKDIR /app
COPY . /app
RUN dotnet restore
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true  
ENV ASPNETCORE_URLS=http://+:80  

